apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "qod-api.fullname" . }}
  labels:
    app: {{ template "qod-api.name" . }}
    chart: {{ template "qod-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "qod-api.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "qod-api.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: DB_HOST
              value: {{ .Values.db.host }}
            - name: DB_USER
              value: {{ .Values.db.user }}
            - name: DB_PASS
              value: {{ .Values.db.pass }}
