# Default values for qod-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ibmicpcoc/qod-db
  tag: 1.0.0
  pullPolicy: IfNotPresent

db:
  password: root