apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: userXX-mcmqod-application
  labels:
    app: qod-app
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - qod-app
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
