apiVersion: v1
kind: Service
metadata:
  name: {{ template "qod-db.name" . }}
  labels:
    app: {{ template "qod-db.name" . }}
    chart: {{ template "qod-db.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql
      protocol: TCP
      
  selector:
    app: {{ template "qod-db.name" . }}
    release: {{ .Release.Name }}
