# Default values for qod-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ibmicpcoc/qod-api
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

db:
  host: qod-db
  user: root
  pass: root